# Generated by Django 4.2.4 on 2025-04-11 11:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='articles',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Time'),
        ),
    ]
